version: "3.9"
services: 
  build: .
  ports: 
    - "8000:80"
  depends_on:
  - db
  environment:
  - ASPNETCORE_ENVIRONMENT=Development
  - ConnectionStrings_DefaultConnection=Server=DESKTOP-F7M6I8G\\SQLEXPRESS;Database=Starbucks;User Id=lizzymr;Password=pass1234*
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - PASS=pass1234*
    ports:
    - "1433:1433"
    volumes:
    - mssqldata: /var/opt/mssql
  volumes:
    mssqldata  